### ISSUE TITLE
3d subplots fail

### ISSUE THREAD

**Issue by jim-bo** [plotly/python-api#158]
I am trying to generate 4, Scatter3d plots tiled like in the example:
https://plot.ly/python/subplots/
However it fails and defaults to 1. I was just wondering if I was doing something wrong or if this just isn't supported yet.

Example:
https://plot.ly/~JamesLindsay/84/i-3-subplots/

```python
    for k in range(2, 6):

        # compute clustering.
        centroid, label, inertia = k_means(V, n_clusters=k)

        # add trace for each component.
        for kidx in range(k):
            traces.append(
                Scatter3d(
                    x = V[label == kidx, 0],
                    y = V[label == kidx, 1],
                    z = V[label == kidx, 2],
                    mode = 'markers',
                    marker = Marker(
                        size = 12,
                        opacity = 0.8,
                    ),
                )
            )

        # change axis pointer.
        aidx += 1

    data = Data(traces)
    fig = get_subplots(rows=2, columns=2)
    fig['data'] += data
    fig['layout'].update(title='i <3 subplots')
```

**Comment by etpinard** [comment]
In version 1.5.0, we've expanded the capabilities of `tls.make_subplots` in a new function called `tls.make_subplots`. 

Among other features, `tls.make_subplots` can generate 3d subplots (or subscenes if you prefer). 

This [notebook](http://nbviewer.ipython.org/github/etpinard/plotly-misc-nbs/blob/master/subplots/make-subscenes.ipynb) walks you through an example.
