### ISSUE TITLE
requirements.txt problem 

### ISSUE THREAD

**Issue by williamratcliff** [plotly/python-api#174]
Hi!  I needed to run plot.ly on a Redhat distribution where there was only python2.6.   In order to use it, I needed to do a pip install of ordereddict.   I also needed to upgrade simplejson (the default version does not have the object_pairs_hook).   Perhaps you could add ordereddict as a requirement along with a version of simplejson that has this keyword (I'm not sure when they added it, so I just grabbed the latest one).   This would make life easier for people.  Thanks!!!!  Excellent product!!!

**Comment by theengineear** [comment]
Yes! You do need those for python 2.6, glad you found them! there was meant to be a 2-6 version of 'requirements.txt', but i don't think it ever got committed. Thanks for the heads up, I'll notify you when it's in updated.

**Comment by theengineear** [comment]
@williamratcliff , #175 closes this issue. These requirements are just going to be downloaded for all python versions since they're already included in stdlib for other versions anyhow. Thanks!
