### ISSUE TITLE
Support drawing Rectangle Figure

### ISSUE THREAD

**Issue by HubLot** [plotly/python-api#191]
Hi, 

For a plot, i would like to highlights some sweet spots in the graph.
With matplotlib, I would use the [Rectangle object](http://matplotlib.org/api/patches_api.html#matplotlib.patches.Rectangle) like this :

    rect = maplotlib.pyplot.Rectangle((0.5, 0.5), 1, -0.04)
    axe.add_artist(rect)

But with plot.ly, I can't figure out how to do this. 
It could be great if you support this matplotlib feature.

**Comment by theengineear** [comment]
@HubLot , This is on Plotly's roadmap for sure. In the interim, you can take a peek at annotations:

https://plot.ly/python/text-and-annotations/

**Comment by HubLot** [comment]
Great! Do you have a slight idea of when?
I start playing with the annotations but the size of the rectangle depends of the text's length then it's a bit tricky to get the right ratio.

Thanks for your work anyway!

**Comment by theengineear** [comment]
To be safe, from the API you can expect this functionality in ~1 month. There may be an experimental version as soon as a couple weeks though.

**Comment by HubLot** [comment]
Great news! Looking forward to play with it
