### ISSUE TITLE
zmin and zmax ignored in Heatmaps

### ISSUE THREAD

**Issue by michaelaye** [plotly/python-api#193]
```python
import numpy as np
import plotly.plotly as py
from plotly.graph_objs import Heatmap,Data
data = np.arange(10000).reshape(100,100)
trace = Heatmap(z=np.flipud(data), zmin=1000, zmax=2000)
py.iplot(Data([trace]))
```
Using version 1.6.6 on Python 3 (miniconda, all updates), IPython 3.0.0dev

**Comment by michaelaye** [comment]
Creates this:
https://plot.ly/~michaelaye/106/

**Comment by etpinard** [comment]
You need to add zauto=False.

**Comment by michaelaye** [comment]
if i set zmin/zmax, isn't it obvious that I don't want zauto?

**Comment by michaelaye** [comment]
i still would call it an API bug then.

**Comment by michaelaye** [comment]
Or a doc's bug, as it's not mentioned in the zmin doctext that zauto needs to be False for it to be accepted.

**Comment by michaelaye** [comment]
but thanks for the very fast reply!

**Comment by etpinard** [comment]
Thanks for the headups. 

I agree. Setting zmin or zmax is obvious enough and zauto=False is redundant. 

This is the api we use for layout.range. If layout.range is supplied by a user then layout .autorange is set to false automatically. 

Moreover, yes, the docstrings for zmin and zmax should mention somthing about zauto. 

Both these *bugs* are not related to code in the python api directly, so I'll close this issue.

Thanks again.

**Comment by felixriese** [comment]
2021 and still not resolved, not even in the documentation. What is the right place to request that feature or to make a pull request?

**Comment by Alexander-Serov** [comment]
Let us revive this. This is a weird behavior. Made me lose 20 mins.

**Comment by empet** [comment]
@felixriese, @Alexander-Serov 
Heatmap zmin, zmax work very well, for years.
Example:
```
import numpy as np
import plotly.graph_objects as go

h = 0.05
y, x = np.mgrid[-5 : 5+h : h, -5 : 10+h : h]
z = np.sin(x)**10 + np.cos(10 + y*x) + np.cos(x) + 0.2*y + 0.1*x
fig=go.Figure(go.Heatmap(z=z, colorscale="turbo"))  #no restrictions
fig.update_layout(width=450, height=450)
```
![default](https://user-images.githubusercontent.com/3627253/142912081-a41fba89-4cd1-468c-9dea-ede8bede0384.png)
```
fig1=go.Figure(go.Heatmap(z=z, colorscale="turbo", zmin=-5, zmax=5))
fig1.update_layout(width=450, height=450)
```
![zmMpm5](https://user-images.githubusercontent.com/3627253/142912189-a378bab7-a25c-454e-85f1-a531723c7528.png)
The same plot (like the last one) you can get setting coloraxis with cmin, cmax, not zmin, zmax:
```
fig2=go.Figure(go.Heatmap(z=z, coloraxis="coloraxis"))
fig2.update_layout(width=450, height=450, coloraxis=dict(colorscale="turbo", cmin=-5, cmax=5))
```
