### ISSUE TITLE
More useful message for folks without a Plotly account (who don't know they need one)

### ISSUE THREAD

**Issue by theengineear** [plotly/python-api#195]
Feedback email:

"I did have a little trouble though — I started with plotly after I forked an ipython notebook that made a plotly based plot. Naturally, I got an error since I didn’t log in. I had no idea I had to set up an account. The error message was something like username can’t be empty…  Perhaps a more useful error message could occur if you try to plot with out an account. (Though I imagine my route to using plotly is not usual) What would get me to only use plotly? I guess a script I could enable to translate all my matplotlib code into plotly. Until then, I think I’ll just be using plotly when I want interactive plots."

**Comment by etpinard** [comment]
:+1:

**Comment by theengineear** [comment]
Gonna close this for now, I just tried using plotly without a .plotly file and got the following error:

```
PlotlyLocalCredentialsError: 
Couldn't find a 'username', 'api-key' pair for you on your local machine. To sign in temporarily (until you stop running Python), run:
>>> import plotly.plotly as py
>>> py.sign_in('username', 'api_key')

Even better, save your credentials permanently using the 'tools' module:
>>> import plotly.tools as tls
>>> tls.set_credentials_file(username='username', api_key='api-key')

For more help, see https://plot.ly/python.
```

Seems pretty helpful! Unless there's another path to unhelpfulness, this seems like a non-issue.

**Comment by kilojoules** [comment]
+1 It wasn't immediately clear to me that plotly needs a login to work. I suggest adding something along the lines of "A valid username and password is necessary to use plotly"
