### ISSUE TITLE
Insecure Platform Warning, Not Data Streamed

### ISSUE THREAD

**Issue by Aidoboy** [plotly/python-api#214]
I'm trying to run the Python streaming tutorial on a Pi, and when I do, I get this, and no data appaers of the web page it makes:
    /usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning:
    
    A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

Does anyone know why?

**Comment by etpinard** [comment]
-> https://github.com/plotly/python-user-guide/issues/15#issuecomment-100037103 <-
