### ISSUE TITLE
Quiver object has no attribute marker size

### ISSUE THREAD

**Issue by jackparmer** [plotly/python-api#216]
![screen shot 2015-05-13 at 3 06 53 pm](https://cloud.githubusercontent.com/assets/1865834/7610920/d6509e98-f980-11e4-8ec3-39c4cd58566c.png)

matplotlib quiver plots:
http://matplotlib.org/examples/pylab_examples/quiver_demo.html

**Comment by cldougl** [comment]
@jackparmer  is this still a bug re matplotlylib or can we close this because it doesn't apply to TraceFactory.create_quiver ?

**Comment by jackparmer** [comment]
we can close
