### ISSUE TITLE
update graph reference

### ISSUE THREAD

**Issue by theengineear** [plotly/python-api#228]
~~This should be fixed in the short-term with an update to our current graph-reference system. However, the long term fix is in the plot.ly frontend code.~~

Nah, we're goin' for it now :)

The goal here is to *only* validate keys for now.

Todo:

- [x] #281 remove streaming validation, it doesn't exist in plot schema
- [x] add local cacheing of plot schema

**Comment by chriddyp** [comment]
@theengineear - are you planning on taking this one?

**Comment by theengineear** [comment]
Yep. This has been waiting for some changes to plot-schema, but I'm actually planning on it for this week. I'll assign myself to make that clearer :)

**Comment by theengineear** [comment]
@chriddyp @cldougl , thoughts?

I should probably share this to make sure I'm on the right track. I'm giving `graph_objs.py` a *huge* overhaul to update the new graph reference stuff. Everything is `path` based. That means that objects know *what* they are by knowing roughly *where* they are in a figure.

One fun add on to this is auto-completion! By overloading attributes/dict keys we can do pretty cool stuff like this now:

```
scatter = go.Scatter()
scatter.marker.line.color = 'red'
scatter.marker.symbol = 'square'
scatter.opacity = .8
scatter.y = [2, 1, 2]
scatter  # {'marker': {'line': {'color': 'red'}, 'symbol': 'square'}, 'opacity': 0.8, 'type': 'scatter', 'y': [2, 1, 2]}
```

Of course the old way of instantiating these works. In addition, you get auto-completion for the old version too:

```
scatter = go.Scatter()
scatter['marker']['line']['color'] = 'red'
scatter['marker']['symbol'] = ' square'
scatter['opacity'] = .8
scatter['y'] = [2, 1, 2]
scatter  # {'marker': {'line': {'color': 'red'}, 'symbol': 'square'}, 'opacity': 0.8, 'type': 'scatter', 'y': [2, 1, 2]}
```

I think this really tightens up the syntax and I've found it a heck of a lot nicer so far!

Final note, if you turn on greedy completion in IPython, `%config IPCompleter.greedy = True`, you get full `tab` completion of all the possible keys. Making chaining attributes through objects super easy to do if you don't know the attributes by heart.

The major downside to using attributes like this is the potential for an attribute and a key to conflict :(. If this happens the `.` will *have* to return the bound method, though the `[]` can still return the overloaded key... not ideal, but non-fatal at least. To my knowledge, we don't have any such collisions and we *could* even be proactive about it if we wanted an put in a Circle test for it... just a thought. I think the `.` syntax with auto-completion really improves code, but I'm open to opposition :)

**Comment by chriddyp** [comment]
```
scatter = go.Scatter()
scatter.marker.line.color = 'red'
```

that's wild that that works. wild!

the `[]`, `.` parallelism is cool, it's just like how pandas references columns. and i love the `tab`-`tab` functionality, that's definitely the best way to learn the language.

**Comment by cldougl** [comment]
I think the `.` syntax looks really clean and the `tab` completion will be so helpful!!

**Comment by theengineear** [comment]
Aight. Object classes are *within 3* \o/. I *think* `angularaxis` and `radialaxis` need to make their way into plot schema still.

The remaining one is `Font`, which requires working in the `defs` from the plot schema. *so close*.
