### ISSUE TITLE
No module named plotly

### ISSUE THREAD

**Issue by danio368** [plotly/python-api#237]
Hi, I am trying to use plotly with Python. 
I think I installed it correctly, I can see Plotly when I list installed modules.
However, I cannot run the sample code provided as a first test.
To be more precise, if I copy paste line by line in the python shell, it works fine, and my graph is created. But, if I create a new python script, with the very same code, saved on my machine, and try to run it, I can an error in the first line "import plotly.plotly", saying that there is no module named plotly.
I really don't understand what may happen. Any help would be very much appreciated.

**Comment by theengineear** [comment]
@danio368 , can you paste the exact exception traceback you get when you run the stand-alone script?

**Comment by danio368** [comment]
Thanks for your answer. I figured it out. Was a stupid Python beginner mistake. I had saved my script with the name of the module ('plotly.py'), which is why Python could not find the module.
Sorry for bothering you

**Comment by chriddyp** [comment]
@danio368 thanks for reporting, a common mistake!

**Comment by danielrussellLA** [comment]
@danio368 thanks for posting! helped me out - there was a file in my directory called plotly.py that was overriding the global module import. good find!

**Comment by VictorCruzIsc** [comment]
I do have the same problem and it is not the file name.

Could you please give me a hand?

This is my exact console output:

python pp.py
Traceback (most recent call last):

```bash
  File "pp.py", line 1, in <module>
    from plotly import __version__
  File "/home/vicco/Desktop/git/plotly/plotly.py", line 1, in <module>
ImportError: No module named plotly
```

**Comment by danielrussellLA** [comment]
@VictorCruzIsc is your app in a folder named plotly? try renaming the file and folder to something else (like /home/vicco/Desktop/git/plotly_app/plotly_stuff.py

**Comment by hahanigehaha233** [comment]
Nice answer!! That confusing me all the morning!!!!

**Comment by pravallika-sreevidyanikethan** [comment]
import plotly

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-c27a4132ad2e> in <module>()
----> 1 import plotly

ModuleNotFoundError: No module named 'plotly'

I installed plotly correctly but still getting the error

**Comment by UtkarshaT** [comment]
<img width="696" alt="Screenshot 2019-12-03 at 10 15 40" src="https://user-images.githubusercontent.com/52493453/70021251-0a581f80-15b6-11ea-9ea3-d07a1053760b.png">

I am still getting this error ...

**Comment by nnadiabfata** [comment]
me too i have the same problem:
ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead. 
also
AttributeError: 'DataFrame' object has no attribute 'iplot'
could you help me i based my project on plotly

**Comment by empet** [comment]
Starting with plotly version 4.0 you have to replace `import plotly.plotly as py`  by  
`import chart_studio.plotly as py` to send a figure to  Plotly cloud.

**Comment by Atashnezhad** [comment]
> Starting with plotly version 4.0 you have to replace `import plotly.plotly as py` by
> `import chart_studio.plotly as py` to send a figure to Plotly cloud.

what about the other commands like 
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

cuz all of above commands results in same issue for me?
Thanks for your help in advance
