### ISSUE TITLE
How to add New Traces with reusing existing plotted data ?

### ISSUE THREAD

**Issue by ahetawal** [plotly/python-api#287]
Hi,
I am following this link to add a new Trace to my existing graph remotely.
https://plot.ly/python/sending-data-to-charts/#add-new-traces-to-a-chart

But as recommended I would prefer to overwrite the whole chart's data, while adding the new data points. 
My limitation is I cannot calculate my older plotted data points for this process to work.
I am trying to find a way to achieve the logic below: 

newData = Data(someData)
plottedData = py.get_figure("url").get_data()
mergedData = plottedData + newData ??

py.plot(mergedData, filename = 'myPlot', fileopt='overwrite', auto_open=False)

BUT, not sure how to perform the mergeData part. 
Is there a way to do this, or you can recommend me some other way to achieve what I am trying to do.

Thank you,

**Comment by chriddyp** [comment]
Hey @ahetawal - check out the examples here: https://plot.ly/python/get-requests/. `fig['data']` is basically just a list of dictionaries (the objects "subclass" dicts and lists) so you can do stuff like:

```
fig['data'][0]['x'].extend([1, 2, 3, 4])
fig['data'][0]['y'].extend([10, 20, 30, 40])
```
