### ISSUE TITLE
Disable a particular legend though api?

### ISSUE THREAD

**Issue by ahetawal** [plotly/python-api#300]
Hi,
I am working on a plot which has lets 3 different categories which are displayed as legends.
But since one of them  is a non-important category, I would like to suppress it when i generate the plot, but would still like to show it. So that users can turn it on or off based on what data to want to see. Is there any way to do this through the api/config?

Sample plot : https://plot.ly/~ahetawal/120/likematch-results-test/
I would like to keep the null category as un-selected by default.

**Comment by chriddyp** [comment]
Hey @ahetawal --

Check out our documentation here: https://plot.ly/python/legend/#hiding-legend-entries. In particular the last example has what you're looking for :)

**Comment by chriddyp** [comment]
Ohhh! Nevermind, I think what you want is different. Set the property "visible" to "legendonly": https://plot.ly/python/reference/#bar-visible.

**Comment by ahetawal** [comment]
Thanks!! This is what I was looking for ....
