### ISSUE TITLE
Setting "Scene Aspect Mode"

### ISSUE THREAD

**Issue by eulerreich** [plotly/python-api#321]
On the plot's full screen page, under the `layout` section, there's an option to set `Scene Aspect Mode` to `auto`, `cube`, etc. How do I set this with the python api?

**Comment by theengineear** [comment]
You may need to upgrade your Python version. The newest version auto-syncs new keys Plotly adds. You should be able to set it at the following path:

`fig['layout']['scene']['aspectmode'] = 'cube'`

In the newest version of the python api you can see keys under objects as follows:

```
import plotly.graph_objs as go

fig = go.Figure()
fig.layout.scene.help()  # will print a list of possible attributes
fig.layout.scene.help('aspectmode')  # will print aspect-mode-specific info.
```

Let me know if that makes sense. This key may not have been recognized before version `1.8.6`. So you may need to `pip install --upgrade plotly` for this to work.

**Comment by eulerreich** [comment]
OK Thanks! This works for me.

**Comment by theengineear** [comment]
awesome! i'll close this, feel free to open future issues up though.

**Comment by chriddyp** [comment]
@eulerreich for future reference, you can find documentation for all the keys in the reference section: https://plot.ly/python/reference
