### ISSUE TITLE
doc typo

### ISSUE THREAD

**Issue by eulerreich** [plotly/python-api#328]
https://plot.ly/python/reference/#scatter-marker-colorbar

It's actually `go.ColorBar`, not `go.Colorbar`. Similar for other appearances.

(Can't find the source for the api doc. Is it not on github?)

**Comment by chriddyp** [comment]
thx @eulerreich ! documentation repo is here: github.com/plotly/documentation/tree/source, I'll reopen over there.

**Comment by eulerreich** [comment]
where is the file located? I tried search phrases from the doc but google got not hits

**Comment by chriddyp** [comment]
@eulerreich - it's autogenerated from our [plot-schema.json](https://plot.ly/plot-schema.json). Here's the fix: https://github.com/plotly/documentation/commit/2a62ac2b8f9ca1944efea03ac854667654251f9c
